GET http://biblionare/books?XDEBUG_SESSION_START=QWERTY&year=1990&country=test&language=test&genre=test
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
Authorization: Bearer Qeofd1EN785nAy524mYJ77ArP3mi7n7h

###

