GET http://biblionare/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
Authorization: Bearer Yt_D41IZSj-Pp5foXdtXd7WR3pHs72B-

###

