POST http://biblionare/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Connection: keep-alive
Accept-Encoding: gzip, deflate, br

{
  "username" : "Vania",
  "password" : "1234"
}

###

