version: '3.2'

services:
  # Контейнер с nginx, для API
  library_nginx:
    build: images/nginx
    volumes:
      - type: bind
        source: ./..
        target: /srv/www/Mega-Project
    networks:
      library:
        ipv4_address: 192.168.75.10

  # Контейтер с кодом API - php-fpm
  library_backend:
    build: images/backend
    volumes:
      - type: bind
        source: ./..
        target: /srv/www/Mega-Project
    networks:
      library:
        ipv4_address: 192.168.75.11

  # Контейтер с MySQL сервером
  library_database:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - type: bind
        source: ./storage/mysql
        target: /var/lib/mysql
    networks:
      library:
        ipv4_address: 192.168.75.12

networks:
  library:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.75.0/24
